# Generated by Django 5.1.2 on 2024-10-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
